version: '3.8'

services:
  web:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-18
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      # - web-node_modules:/app/node_modules
      # - web-next:/app/.next
    env_file:
      - ./.env.docker.local
    depends_on:
      - db

    # keep container running
    command: /bin/sh -c "while sleep 1000; do :; done"
  
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  web-node_modules:
  web-next:
  db:
